services:
  - type: web
    name: thelearninghouse-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn services.api.db.auth:app --host 0.0.0.0 --port 8503
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DB
        sync: false
      - key: AUTH_TOKEN
        sync: false
      - key: SECRET_TOKEN
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: REGION_NAME
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_HOST
        sync: false
      - key: QDRANT_API_KEY
        sync: false
    healthCheckPath: /docs
    autoDeploy: true